Dockerfile.rhel

Similar to https://github.com/openshift/prometheus/pull/21:
> We need `promu` to build Prometheus but we should use the promu package instead of the upstream version because 1) we're not allowed to download stuff from the outside and 2) this promu version generates proper binaries for OCP (eg dynamically linked with glibc).
cc @sosiouxme

Install promu package for OCP multistage builds

---

.promu.yml

Need to set these back to use the vendor dir until we upgrade to go 1.11

fix build data variables to work with go 1.10

---

Dockerfile.ocp
text_collectors/virt.sh

`virt-what` performs heuristic detection within a VM to detect known virtualization platforms. It may report one or more tags indicating the presence of virtualization. Use the output to write a series per tag as `virt_platform{type="<tag>"} 1`.
Update the dockerfile to have this script present. An init container can call this script to get the virtualization metrics generated into the current working directory.
/assign @pgier

text_collectors: Add a virtualization metric series from virt-what

---

text_collectors/virt.sh

Overwriting each time vs appending
/assign @pgier
Caused only a single final metric to be reported

text_collectors: Fix virt.sh to include help text

---

text_collectors/virt.sh

We will then be able to detect bare metal by the presence of none.
/assign @pgier 
Caught this while finishing out verification (bare metal tests were down all week).

Bug 1773243: If no virt platform is detected, set type to 'none'

---

text_collectors/virt.sh

Fix cases where virtwhat returns multiple detected platforms.
Also provide a default path to TMPDIR in case the environment var isn't set.

Bug 1775454: virtwhat multiple platform

---

Dockerfile.ocp
text_collectors/virt.sh

virt-what performs heuristic detection within a VM to detect known 
virtualization platforms. It may report one or more tags indicating the
presence of virtualization. Use the output to write a series per tag as
`virt_platform{type="<tag>"} 1`.
Update the dockerfile to have this script present.

Bug 1773246: Add a virtualization metric series from virt-what

---

text_collectors/virt.sh

When we fixed the bug with lists of items, we broke the 'none' case
for when there are no virt platforms. Correct this to report none
when no individual platforms are detected.

Bug 1789083: Not reporting 'none' when no platforms located

---

collector/cpu_linux.go

On an IBM Z system it was observed that the parsecpuinfo function was crashing because the parsing of the CPU info is specific to x86 today - https://bugzilla.redhat.com/show_bug.cgi?id=1789260. For now, the short term fix is to disable cpu info metrics on non x86 arches and in the meanwhile we can work on the fix for supporting cpu info metric reporting for multi-arches.

Disable cpu info metric on non x86 arches

---

text_collectors/virt.sh

These detection criteria allow us to better guess at the platform
virt type for the two clouds.

text_collectors: Detect AWS and GCP virt platform type

---

text_collectors/virt.sh

dmidecode returns info about openstack compute, use it to fingerprint
OpenStack specifically.

Bug 1799718: Detect OpenStack virt type nodes

---

text_collectors/virt.sh

Gather bios, baseboard, and system product/vendor/version info to assist debugging failures in specific hardware configurations. Is only gathered on bare metal since virtual environments will not return meaningful info.
In practice I expect the cardinality of this to be <10 series for the vast majority of clusters.  I could imagine a few hodgepodge clusters, but the odds of a single large cluster having unique hardware for every node (on meaningful cluster sizes) is very small.  And a cluster with hundreds of unique hardware configurations would almost certainly be a very strong pathological signal.
/hold
while i test on baremetal

Bug 1804012: On bare metal, detect system info

---

text_collectors/virt.sh

virt-what now detects AWS, we can safely ignore it if it is already
present in the file.

Bug 1803058: text_collectors: Don't detect AWS twice when virt-what is upgraded

---

Dockerfile.ocp

Updating golang-github-prometheus-node_exporter builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/golang-github-prometheus-node_exporter.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.

Updating golang-github-prometheus-node_exporter builder & base images to be consistent with ART

---

Dockerfile.ocp
text_collectors/boots.sh
text_collectors/virt.sh

This text collector reads from /var/log/wtmp (assumed mounted into
the proper spot) and outputs a metric for the number of reboots in
that log. On RHCOS utmp is automatically rotated.
Without https://github.com/openshift/cluster-monitoring-operator/pull/1017 wtmp is empty
During a cluster launch, we reboot once.  I then rebooted twice more.  The boots number excludes the current count, which ensures that when wtmp is rotated that we get a proper counter reset (machine that has node_boots 2 has 3 entries in wtmp including the current, then a rotation happens and they have 1 entry, so node_boots becomes 0, so the total boots is still 3 (2 + counter reset 0 + 1 current boot)
This allows us to estimate the disruption caused by system reboots.

Bug 1906570: Capture the number of boots by reading wtmp

---

collector/netclass_linux.go
go.mod
go.sum
vendor/github.com/prometheus/procfs/Makefile
vendor/github.com/prometheus/procfs/Makefile.common
vendor/github.com/prometheus/procfs/README.md
vendor/github.com/prometheus/procfs/doc.go
vendor/github.com/prometheus/procfs/fixtures.ttar
vendor/github.com/prometheus/procfs/mdstat.go
vendor/github.com/prometheus/procfs/net_ip_socket.go
vendor/github.com/prometheus/procfs/proc_stat.go
vendor/github.com/prometheus/procfs/sysfs/class_cooling_device.go
vendor/github.com/prometheus/procfs/sysfs/class_fibrechannel.go
vendor/github.com/prometheus/procfs/sysfs/class_infiniband.go
vendor/github.com/prometheus/procfs/sysfs/class_power_supply.go
vendor/github.com/prometheus/procfs/sysfs/class_powercap.go
vendor/github.com/prometheus/procfs/sysfs/class_thermal.go
vendor/github.com/prometheus/procfs/sysfs/clocksource.go
vendor/github.com/prometheus/procfs/sysfs/doc.go
vendor/github.com/prometheus/procfs/sysfs/fs.go
vendor/github.com/prometheus/procfs/sysfs/net_class.go
vendor/github.com/prometheus/procfs/sysfs/system_cpu.go
vendor/github.com/prometheus/procfs/sysfs/vmstat_numa.go
vendor/github.com/prometheus/procfs/sysfs/vulnerability.go
vendor/modules.txt

This is a cherry-pick of https://github.com/prometheus/node_exporter/pull/2033

Bug 1984030: netclass: retrieve interface names and filter before parsing

---

collector/rapl_linux.go

The original commit:
[rapl_collector: fix issue with invalid metric name (#2299)](https://github.com/prometheus/node_exporter/pull/2372/commits/0e320e725b5e2f9092b95f4d9f640ff08cf61683)

[OCPBUGS-1044] Fix a bug of metric format on AMD EPYC platforms

---

collector/rapl_linux.go

This PR backports the fix to the release-4.11 branch
The PR to master branch:
https://github.com/openshift/node_exporter/pull/107
The original commit:
[rapl_collector: fix issue with invalid metric name (#2299)](https://github.com/prometheus/node_exporter/pull/2372/commits/0e320e725b5e2f9092b95f4d9f640ff08cf61683)

OCPBUGS-1723: Fix a bug of metric format on AMD EPYC platforms

---

collector/accelerators.go
collector/accelerators_test.go
collector/fixtures/sys.ttar

The new collector counts the number of accelerator PCI device on the node, and creates a new counter metric based on the accelerator type. The acelerators are collected based on the vendor id and device id predefined in a map. The metric contains a label (type) per each accelerator version. Adding new accelerator(s) requires just updating/creating new vendorID/deviceID map, without additional changes to the code

MON-4077: Adding accelerators counter collector metric

---

collector/accelerators.go
collector/accelerators_test.go
collector/testdata/accelerators_test_data.yaml
collector/testdata/accelerators_test_data_duplicated_device_ids.bad.yaml
collector/testdata/accelerators_test_data_duplicated_vendors.bad.yaml
go.mod

accelerator collector needs to have a configuration that describes which vendors and models it should collect. This PR add loading that data from a file. Eventually this file be a configmap mapped into the node-exporter pod.
Parsing the configmap file is done in the init function. The file is defined by an environment variable. This variable will be configured by CMO and by unit-test

MGMT-19498:Add configmap support to the accelerator's collector
